// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_understanding = "CgkI64Xdv_8ZEAIQBg"; // <GPGSID>
        public const string leaderboard_least_deaths = "CgkI64Xdv_8ZEAIQBA"; // <GPGSID>
        public const string achievement_effort = "CgkI64Xdv_8ZEAIQCw"; // <GPGSID>
        public const string achievement_intention = "CgkI64Xdv_8ZEAIQBw"; // <GPGSID>
        public const string achievement_mindfulness = "CgkI64Xdv_8ZEAIQDA"; // <GPGSID>
        public const string achievement_livelihood = "CgkI64Xdv_8ZEAIQCg"; // <GPGSID>
        public const string leaderboard_highest_scores = "CgkI64Xdv_8ZEAIQAg"; // <GPGSID>
        public const string achievement_speech = "CgkI64Xdv_8ZEAIQCA"; // <GPGSID>
        public const string achievement_action = "CgkI64Xdv_8ZEAIQCQ"; // <GPGSID>
        public const string leaderboard_best_times = "CgkI64Xdv_8ZEAIQAw"; // <GPGSID>
        public const string achievement_concentration = "CgkI64Xdv_8ZEAIQDQ"; // <GPGSID>
        public const string achievement_unfolded_and_ascended = "CgkI64Xdv_8ZEAIQDg"; // <GPGSID>
        public const string achievement_no_such_thing_as_luck = "CgkI64Xdv_8ZEAIQDw"; // <GPGSID>

}

